name: release
description: release assets on tag

inputs:
  binary:
    description: path to a binary
    required: true

runs:
  using: composite
  steps:
    # archive
    - if: runner.os != 'Windows'
      run: zip ${{ inputs.binary }}.zip ${{ inputs.binary }} LICENSE README.md
      shell: bash
    - if: runner.os == 'Windows'
      run: powershell Compress-Archive -Path ${{ inputs.binary }}.exe,LICENSE,README.md -DestinationPath ${{ inputs.binary }}.zip
      shell: bash

    # digest
    - if: runner.os != 'macOS'
      run: sha256sum -b ${{ inputs.binary }}.zip > ${{ inputs.binary }}.zip.sha256
      shell: bash
    - if: runner.os == 'macOS'
      run: shasum -a 256 -b ${{ inputs.binary }}.zip > ${{ inputs.binary }}.zip.sha256
      shell: bash
    - run: cat ${{ inputs.binary }}.zip.sha256
      shell: bash

    # upload
    - if: startsWith(github.ref, 'refs/tags/')
      run: gh release upload "${GITHUB_REF/refs\/tags\//}" ${{ inputs.binary }}.zip ${{ inputs.binary }}.zip.sha256
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
