name: release
description: release assets

inputs:
  binary:
    description: path to a binary
    required: true
  dry-run:
    description: set false to upload an archive
    required: false
    default: ${{ startsWith(github.ref, 'refs/tags/') }}

runs:
  using: composite
  steps:
    # archive
    - if: runner.os != 'Windows'
      run: zip ${{ inputs.binary }}.zip ${{ inputs.binary }} LICENSE README.md
      shell: bash
    - if: runner.os == 'Windows'
      run: powershell Compress-Archive -Path ${{ inputs.binary }}.exe,LICENSE,README.md -DestinationPath ${{ inputs.binary }}.zip
      shell: bash

    # digest
    - if: runner.os != 'macOS'
      run: sha256sum -b ${{ inputs.binary }}.zip ${{ inputs.binary }}.zip.sha256
      shell: bash
    - if: runner.os == 'macOS'
      run: shasum -a 256 -b ${{ inputs.binary }}.zip > ${{ inputs.binary }}.zip.sha256
      shell: bash

    # upload
    - if: inputs.dry-run == false
      run: gh release upload "${GITHUB_REF##*/}" ${{ inputs.binary }}.zip ${{ inputs.binary }}.zip.sha256
      shell: bash
