name: setup
description: setup Go and cache

inputs:
  go-version:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg
          ~/.cache/go-build
        key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-${{ runner.os }}-
