name: release

on:
  pull_request:
    paths:
      - release/**
  push:
    branches:
      - v1
    tags:
      - test/release/*
    paths:
      - release/**

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
          - runs-on: windows-latest
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup
        with:
          go-version: 1.17
      - run: go build
      - uses: ./release
        with:
          binary: go-actions
