name: setup

on:
  pull_request:
    paths:
      - .github/workflows/setup.yaml
      - setup/**
  push:
    branches:
      - v1
    paths:
      - .github/workflows/setup.yaml
      - setup/**

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup
        with:
          go-version: 1.17
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup
        with:
          go-version: 1.17
      - run: go build
